version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: all
    labels: [dependencies, automerge]

  - package-ecosystem: npm
    directory: '/packages/ai-sdk-ollama'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: all
    labels: [dependencies, automerge]
